# vim: ft=python
# $Id$
# Copyright (C) 2004 Scott Lamb <slamb@slamb.org>.
# This file is part of sigsafe, which is released under the MIT license.

Import('env os_name')
env = env.Copy()

# TODO: make a configure-style test for nanosleep/librt
if os_name == 'osf1':
    env.Append(LIBS = ['rt'])

for i in ['blocked_alarm',
          'setitimer_rounding',
          'socket_timeout',
          'sigsuspend']:
    env.Program(target = 'test_' + i, source = 'test_' + i + '.c')

# Not compiling (at least for now) test_trap_throw - it requires some weird
# compiler options.
