# vim: ft=python
# $Id$
# Copyright (C) 2004 Scott Lamb <slamb@slamb.org>.
# This file is part of sigsafe, which is released under the MIT license.

SConscript('race_checker/SConscript')

Import('env')
env = env.Copy()

for i in ['blocked_alarm', 'setitimer_rounding']:
    env.Program(target = 'test_' + i, source = 'test_' + i + '.c')
