# vim: ft=python
# $Id$
# Copyright (C) 2004 Scott Lamb <slamb@slamb.org>.
# This file is part of sigsafe, which is released under the MIT license.

Import('env os_name')
env = env.Copy()
env.Prepend(LIBS = ['sigsafe'])
env.Program(target = 'race_checker', source = [
    'race_checker.c',
    'races_generic.c',
    'races_io.c',
    ('trace_%s.c' % (os_name)),
])
