# vim: ft=python
# $Id$

Import('env')
env = env.Copy()
env.Prepend(LIBS = ['sigsafe'])
env.Program(target = 'race_checker', source = [
    'race_checker.c',
    'races_generic.c',
    'races_io.c',
    #'#/build-ppc-darwin-debug/sigsafe.c',
    #'#/build-ppc-darwin-debug/ppc-darwin/sighandler_platform.c',
    #'#/build-ppc-darwin-debug/ppc-darwin/sigsafe_read.S',
])
