# vim: ft=python
# $Id$

Import('env')
Import('arch')
Import('os_name')

platform_subdir = arch + '-' + os_name

source = [
    'sigsafe.c',
    platform_subdir + '/sighandler_platform.c',
    platform_subdir + '/sigsafe_read.S'
]

env.StaticLibrary(target = 'sigsafe', source = source)
#env.SharedLibrary(target = 'sigsafe', source = source)
